name: CI
on:
  push:
    branches:
      - feat/distributed-build
  pull_request:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

jobs:
  setup-trace:
    runs-on: ubuntu-latest
    outputs:
      TRACEPARENT: ${{ steps.setup-trace-step.outputs.TRACEPARENT}}
    env:
      HONEYCOMB_DATASET: nx-test
      HONEYCOMB_WRITEKEY: ${{ secrets.HONEYCOMB_WRITEKEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Trace
        id: setup-trace-step
        run: sh ./tools/scripts/setup-trace.sh
  task-scheduler:
    runs-on: ubuntu-latest
    needs: [setup-trace]
    env:
      TRACEPARENT: ${{ needs.setup-trace.outputs.TRACEPARENT }}
      HONEYCOMB_DATASET: nx-test
      HONEYCOMB_WRITEKEY: ${{ secrets.HONEYCOMB_WRITEKEY }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout branch
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'feat/distributed-build'
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: sh tools/scripts/install-otel-cli.sh
      - run: npx nx-cloud start-ci-run
      - run: |
          otel-cli exec \
            -n nx-cli \
            -s build-task \
            --otlp-headers "x-honeycomb-team=$HONEYCOMB_WRITEKEY,x-honeycomb-dataset=$HONEYCOMB_DATASET" \
            --endpoint api.honeycomb.io:443 \
            "npx nx run-many --target=build --all --max-parallel=3"
      - run: npx nx-cloud stop-all-agents
        if: always()
  agents:
    needs: [setup-trace]
    runs-on: ubuntu-latest
    name: Agent
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2, 3]
    env:
      TRACEPARENT: ${{ needs.setup-trace.outputs.TRACEPARENT }}
      HONEYCOMB_DATASET: nx-test
      HONEYCOMB_WRITEKEY: ${{ secrets.HONEYCOMB_WRITEKEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
