name: CI
on:
  push:
    branches:
      - master
  pull_request:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

jobs:
  setup-trace:
    runs-on: ubuntu-latest
    outputs:
      TRACEPARENT: ${{ steps.setup-trace-step.TRACEPARENT}}
      HONEYCOMB_DATASET: nx-test
      HONEYCOMB_WRITEKEY: ${{ secrets.HONEYCOMB_WRITEKEY }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [master]
        with:
          fetch-depth: 0
      - name: Setup Trace
        id: setup-trace-step
        run: sh ./tools/scripts/setup-trace.sh
  master:
    runs-on: ubuntu-latest
    needs: [setup-trace]
    env:
      TRACEPARENT: ${{ needs.setup-trace.TRACEPARENT }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [master]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npx nx-cloud start-ci-run
      - run: npx nx run-many --target=build --all
      - run: npx nx run-many --target=test --all
      - run: npx nx-cloud stop-all-agents
  agents:
    needs: [setup-trace]
    runs-on: ubuntu-latest
    name: Agent
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2, 3]
    env:
      TRACEPARENT: ${{ needs.setup-trace.TRACEPARENT }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
